### ISSUE TITLE
end point for trending topic / hashtag

### ISSUE THREAD

**Issue by minhe7735** [052223-java-angular/Flumblr-Backend#53]
Criteria: Create endpoints which lets users view queried feed that is either by hashtag, or by trending.

SP:2

Acceptance: Endpoints can be successfully used and retrieved.

**Comment by sebshader** [comment]
isn't this done? we have the 'trending' and 'tag' endpoints under 'post' now

**Comment by sebshader** [comment]
or is this for a feed of tags rather than a feed of posts?

**Comment by minhe7735** [comment]
yeah it's done
